import type { ExportExperience } from '../export/projection';
import type { RecipientScene, ExperienceStrategy } from '../engines/scenes';
import { publicCoreMessage } from '../engines/scenes';
import { escapeHtml as e } from './text';

export function renderRevisionScene(
  scene: RecipientScene,
  gift: ExportExperience,
  strategy: ExperienceStrategy,
  renderBlocks: (items: ExportExperience['blocks']) => string,
): string {
  const concept = gift.plan!.concept;
  const box = concept === 'surprise-box';
  const cinema = concept === 'light-premiere';
  const name = gift.blocks.find((b) => b.type === 'intro')?.data.name ?? '';
  const core = publicCoreMessage(gift);
  const content = renderBlocks(scene.blocks);
  switch (scene.id) {
    case 'opening':
      return `<p class="time-welcome"><span id="time-greeting">Willkommen</span><time id="live-clock" aria-label="Aktuelle Uhrzeit"></time></p><div class="revision-opening" aria-hidden="true"><span class="paper-half"></span><span class="paper-half"></span><span class="opening-seal">${box ? '✦' : cinema ? '·' : 'B'}</span></div><div class="revision-intro"><p class="eyebrow">${box ? 'Hier steckt etwas für dich drin' : cinema ? 'Eine Premiere. Nur für dich.' : 'Ein Moment. Nur für dich.'}</p><h1>${e(name)}</h1><p>${box ? 'Du entscheidest, welches Fach zuerst aufgeht.' : cinema ? 'Das Licht geht an. Alles andere darf kurz warten.' : 'Nicht alles auf einmal. Ein kleiner Anfang.'}</p></div>`;
    case 'choice': {
      const order = gift.plan!.sceneOrder;
      const available = order.slice(order.indexOf('choice') + 1, -2);
      const options = available
        .map((role, index) => {
          const photo = role === 'moments';
          const words = role === 'letter';
          const label = photo
            ? 'Das Bild entdecken'
            : words
              ? 'Die Worte öffnen'
              : 'Den Wunsch auspacken';
          const echo = words
            ? core
            : (gift.blocks
                .find((b) => b.type === 'wish')
                ?.data.text.slice(0, 240) ?? core);
          return `<button data-choice="${['warm', 'joy', 'wonder'][index]}" data-route="${role}" data-final-focus="${photo ? 'photo' : 'words'}" data-echo="${e(echo)}" aria-pressed="false"><span aria-hidden="true">${photo ? '▧' : words ? '✉' : '✦'}</span><strong>${label}</strong></button>`;
        })
        .join('');
      return `<div class="revision-choice"><p class="eyebrow">${box ? 'Dein erstes Fach' : cinema ? 'Wohin fällt das Licht?' : 'Dein Blick entscheidet'}</p><h2>${box ? 'Womit fängst du an?' : cinema ? 'Führe das Licht.' : 'Was möchtest du zuerst entdecken?'}</h2><div class="recipient-choices">${options}</div><p id="choice-response" role="status">Deine Wahl öffnet diesen Inhalt sofort und bewahrt ihn im Schlussbild. Die anderen Inhalte bleiben erreichbar.</p></div>`;
    }
    case 'moments':
      return `<p id="moment-intro" class="scene-lead">${box ? 'Das Bildfach ist offen.' : cinema ? 'Ein Bild im Licht.' : 'Platz für den ganzen Moment.'}</p><div class="photo-deck">${scene.blocks.map((block, index) => `<div data-photo="${index}">${renderBlocks([block])}</div>`).join('')}</div>${scene.blocks.length > 1 ? `<div class="photo-select" aria-label="Fotos erkunden">${scene.blocks.map((_, index) => `<button data-photo-select="${index}" aria-pressed="${index === 0}">Bild ${index + 1}</button>`).join('')}</div>` : ''}`;
    case 'letter':
      return `<div class="revision-letter"><p class="eyebrow">${box ? 'Das Wortfach' : cinema ? 'Das Licht wird ruhig' : 'Diese Worte bekommen ihren Platz'}</p><details class="letter-reveal"><summary>${strategy.respectful ? 'Den persönlichen Gruß öffnen' : 'Deine Worte entfalten'}</summary>${content}</details></div>`;
    case 'surprise':
      return `<div class="revision-wish"><span class="wish-mark" aria-hidden="true">✦</span><p class="eyebrow">Zum Mitnehmen</p>${content}</div>`;
    case 'finale':
      return `<div class="cinematic-finale revision-finale"><div class="finale-orbit" aria-hidden="true"></div><div class="finale-message"><p class="eyebrow">${box ? 'Die Teile werden ein Geschenk' : cinema ? 'Das Licht verbindet die Momente' : 'Was du behalten möchtest'}</p><h2>${box ? 'Ein guter Anfang.<br>Ein neues Jahr.' : cinema ? 'Ein letzter Lichtblick.' : 'Ein Moment wird groß.'}</h2><p class="choice-echo">Dein Geschenk. In deinem Tempo.</p></div><div class="finale-message"><div data-revision-photo></div><blockquote class="core-message" data-final-words><p>„${e(core)}“</p></blockquote></div><div class="finale-message"><p class="eyebrow">${box ? 'Dein Geburtstagsbanner' : 'Für dich gemacht'}</p><h1>Alles Gute<br>zum Geburtstag${name ? `,<br><em>${e(name)}</em>` : ''}.</h1><div data-revision-final-keepsake></div><p class="final-sentence" data-final-sentence>${e(core)}</p></div></div><div class="finale-controls"><button id="skip-finale" class="subtle-button">Abschluss sofort ansehen</button>${box || (cinema && !strategy.respectful) ? '<button id="fireworks-again" class="subtle-button">Noch einmal feiern</button>' : ''}<span id="finale-status" role="status">Dein Moment – ohne Eile und jederzeit überspringbar.</span></div>`;
    case 'closing':
      return `<div class="closing-copy revision-closing">${content}<p class="eyebrow">Zum Behalten</p><div data-revision-final-keepsake></div><p class="final-sentence" data-final-sentence>${e(core)}</p><p>${box ? 'Das Konfetti vergeht. Deine Worte bleiben.' : cinema ? 'Das Licht wird still. Dein Geschenk bleibt hier.' : 'Ein kleiner Moment, der bleiben darf.'}</p><button id="replay" class="subtle-button">Noch einmal erleben</button></div>`;
    default:
      return content;
  }
}

export const REVISION_CSS = `
body[data-concept]{--bg:#f6efe4;--ink:#412d24;--gold:#92533d;--gold-light:#dfaa8d;--card:#fffaf2;--accent:#92533d;background:var(--bg);font-family:system-ui,sans-serif}
body[data-concept] .gift-stage{max-width:1000px;padding-top:12px}body[data-concept] .gift-scene,body[data-concept][data-generated-animation] .gift-scene{padding:24px 0;width:100%;max-width:none;background:none;border:0;border-radius:0;box-shadow:none;overflow:visible}body[data-concept] .gift-scene:before{display:none}body[data-concept] .scene-heading{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)}body[data-concept] .revision-intro{text-align:center}body[data-concept] .revision-intro h1{font-size:clamp(3.4rem,12vw,7rem);letter-spacing:-.05em;margin:24px 0}body[data-concept] .light-reflection,body[data-concept] .gold-field{display:none}body[data-concept] .stage-header{background:var(--bg)}body[data-concept] .stage-nav{background:var(--card);border-color:var(--gold)}body[data-concept] .stage-nav #stage-next{background:var(--gold);color:white}body[data-concept] .subtle-button,body[data-concept] .letter-reveal{background:var(--card);color:var(--ink);border-color:var(--gold)}
.revision-opening{height:180px;max-width:320px;margin:20px auto;position:relative;display:grid;place-items:center;overflow:hidden}.paper-half{position:absolute;inset:0 50% 0 0;background:#e7d7be;transform:skewY(-8deg);animation:none}.paper-half:nth-child(2){inset:0 0 0 50%;transform:skewY(8deg);animation:none}.opening-seal{border-radius:50%;width:52px;height:52px;display:grid;place-items:center;background:var(--gold);color:white;font:25px Georgia;position:relative}.revision-choice{text-align:center}.revision-choice h2{font-size:clamp(2rem,6vw,3.2rem)}body[data-concept] .recipient-choices{display:flex;flex-wrap:wrap;justify-content:center;gap:18px}body[data-concept] .recipient-choices button{flex:1 1 150px;max-width:300px;background:transparent;border:1px solid var(--gold);border-radius:0;min-height:150px;color:var(--ink);padding:24px 18px}body[data-concept] .recipient-choices button span{display:block;font:3rem Georgia;margin-bottom:12px}body[data-concept] .photo-deck .photo-card{max-width:none;transform:none;margin:0;border:0;background:transparent;padding:0;box-shadow:none}body[data-concept] .photo-deck .photo-image{width:100%;aspect-ratio:auto;max-height:65svh;object-fit:contain;border-radius:0}body[data-concept] .photo-deck figcaption{padding:18px;text-align:center}.revision-letter{max-width:760px;margin:30px auto}.revision-letter>.eyebrow{text-align:center}body[data-concept] .letter-reveal{padding:20px 8px;border:0;border-block:1px solid var(--gold);border-radius:0;background:none;box-shadow:none}body[data-concept] .letter-reveal .card{background:none;border:0;box-shadow:none;padding:12px 0}body[data-concept] .letter-reveal .card p{animation:none!important}.revision-wish{text-align:center}.wish-mark{font-size:4rem;color:var(--gold)}body[data-concept] .revision-wish .card{background:none;border:0;box-shadow:none}.revision-finale{isolation:isolate}body[data-concept] .cinematic-finale{min-height:55svh}body[data-concept] .core-message{margin:20px auto;font-size:clamp(1.8rem,5vw,3.1rem)}[data-revision-final-keepsake] img{display:block;max-height:26svh;max-width:100%;width:auto;margin:12px auto;object-fit:contain}.final-sentence{font-size:1rem;max-width:650px;margin:18px auto}body[data-final-focus="words"] [data-revision-final-keepsake],body[data-final-focus="photo"] [data-final-sentence]{display:none}[data-revision-photo] img{display:block;max-width:100%;width:auto;max-height:45svh;object-fit:contain;margin:18px auto}body[data-final-focus="words"] [data-revision-photo]{display:none}body[data-final-focus="photo"] [data-final-words]{font-size:1rem}body[data-concept] .finale-orbit{animation:final-light 1800ms ease-out both}body[data-concept] .revision-closing{max-width:720px;margin:0 auto}
body[data-concept="surprise-box"]{--bg:#fff2e6;--ink:#142c7a;--gold:#17388b;--gold-light:#f78059;--card:#fffaf4;--accent:#17388b}body[data-concept="surprise-box"] h1,body[data-concept="surprise-box"] h2{font-family:system-ui,sans-serif;font-weight:650}body[data-concept="surprise-box"] .revision-opening{background:#f57b57;transform:rotate(-3deg);width:230px}body[data-concept="surprise-box"] .paper-half{background:#17388b;inset:0 44%}body[data-concept="surprise-box"] .opening-seal{background:#ffde6b;color:#142c7a}body[data-concept="surprise-box"] .recipient-choices button{background:#f78059;transform:rotate(-3deg);border:0;box-shadow:8px 8px #142c7a15}body[data-concept="surprise-box"] .recipient-choices button:nth-child(2){background:#ffde6b;transform:rotate(3deg)}body[data-concept="surprise-box"] .recipient-choices button:nth-child(3){background:#b5ded1}body[data-concept="surprise-box"] .photo-deck .photo-card{padding:16px;background:white;margin:20px auto;max-width:680px;transform:rotate(-2deg);box-shadow:10px 12px #142c7a12}body[data-concept="surprise-box"] .letter-reveal{background:#fffaf4;border-bottom:7px solid #f78059;padding:22px}body[data-concept="surprise-box"] .finale-message h1{background:#ffde6b;padding:20px;transform:rotate(-3deg);box-shadow:10px 12px #f78059}body[data-concept="surprise-box"] .finale-message.active{animation:banner-join 650ms ease-out both}
body[data-concept="light-premiere"]{--bg:#111827;--ink:#fff3dc;--gold:#f1bd88;--gold-light:#ffe2b6;--card:#20283a;--accent:#f1bd88;background:radial-gradient(ellipse at 50% 25%,#333148,var(--bg) 70%)}body[data-concept="light-premiere"] .stage-nav #stage-next{color:#111827}body[data-concept="light-premiere"] .revision-opening{overflow:visible}body[data-concept="light-premiere"] .paper-half{display:none}body[data-concept="light-premiere"] .opening-seal{width:20px;height:20px;font-size:0;box-shadow:0 0 75px 40px #f1bd8833;animation:light-open 900ms ease-out both}body[data-concept="light-premiere"] .recipient-choices button{border-radius:50%;width:150px;max-width:210px;background:radial-gradient(circle,#f1bd8822,transparent)}body[data-concept="light-premiere"] .photo-deck .photo-image{max-height:70svh}body[data-concept="light-premiere"] .finale-orbit{background:radial-gradient(ellipse,#f1bd882a,transparent 65%)}body[data-concept="light-premiere"] .finale-message.active{animation:light-connect 1200ms ease-out both}
body[data-opened="true"] .paper-half{animation:paper-part 650ms ease-out both}body[data-opened="true"] .paper-half:nth-child(2){animation-name:paper-part-right}
@keyframes paper-part{to{transform:translateX(-120%) skewY(-8deg)}}@keyframes paper-part-right{to{transform:translateX(120%) skewY(8deg)}}@keyframes banner-join{from{transform:translateY(18px) rotate(-2deg)}to{transform:none}}@keyframes light-open{from{opacity:.2;box-shadow:0 0 0 0 #f1bd8833}to{opacity:1}}@keyframes light-connect{from{opacity:.4;filter:brightness(.75)}to{opacity:1;filter:none}}@keyframes final-light{from{opacity:.2}to{opacity:1}}
body[data-concept][data-paused="true"] *,body[data-concept][data-scene="letter"] *{animation:none!important;transition:none!important}@media(prefers-reduced-motion:reduce){body[data-concept] *{animation:none!important;transition:none!important}}@media(max-width:640px){body[data-concept] .gift-stage{padding-left:max(20px,env(safe-area-inset-left));padding-right:max(20px,env(safe-area-inset-right))}.revision-opening{height:130px;margin:10px auto}body[data-concept] .recipient-choices button{min-height:140px;max-width:none;flex-basis:40%;font-size:.9rem;padding:16px 10px}body[data-concept] .photo-deck .photo-image{max-height:55svh}body[data-concept] .revision-intro h1{font-size:clamp(2.8rem,13vw,5rem)}}`;
